### ISSUE TITLE
ui5 serve doesn't work for ui5-task-nwabap-deployer

### ISSUE THREAD

**Issue by sanjoy0308** [pfefferf/ui5-nwabap-deployer#22]
`"devDependencies": {
	"ui5-task-nwabap-deployer": "*"
},
"ui5": {
	"dependencies": [
		"ui5-task-nwabap-deployer"
	]
}`

If I remove this part from package.json and run npm install, after that ui5 serve works.

**Comment by pfefferf** [comment]
What error you get? What UI5 tooling version you are using? How does your configuration looks like? ...

**Comment by sanjoy0308** [comment]
Hi Florian,

The sap library resources are misaligned if I keep "ui5-task-nwabap-deployer" and see this error in the browser console. 
GET http://localhost:8080/resources/sap-ui-core.js net::ERR_ABORTED 404 (Not Found)

ui5 tooling version is latest ("2.4.0")
`{
	"name": "xxxxxxx",
	"version": "1.0.0",
	"description": "xxxxxxx",
	"main": "index.js",
	"scripts": {
		"test": "echo \"Error: no test specified\" && exit 1"
	},
	"repository": {
		"type": "git",
		"url": "xxxxxxx"
	},
	"keywords": [],
	"author": "",
	"license": "ISC",
	"dependencies": {
		"@openui5/sap.f": "*",
		"@openui5/sap.m": "*",
		"@openui5/sap.tnt": "*",
		"@openui5/sap.ui.core": "*",
		"@openui5/sap.ui.layout": "*",
		"@openui5/sap.ui.table": "*",
		"@openui5/sap.ui.testrecorder": "*",
		"@openui5/sap.ui.unified": "*",
		"@openui5/sap.uxap": "*",
		"@openui5/themelib_sap_fiori_3": "*",
		"@sapui5/sap.ui.comp": "*",
		"@ui5/cli": "*",
		"@ui5/server": "*",
		"@ui5/uiveri5": "*"
	},
	"devDependencies": {
		"ui5-task-nwabap-deployer": "*"
	},
	"ui5": {
		"dependencies": [
			"ui5-task-nwabap-deployer"
		]
	}
}`

**Comment by pfefferf** [comment]
Can you show your ui5.yaml file too please.

**Comment by sanjoy0308** [comment]
```
specVersion: '2.1'
metadata:
  name: xxxxx
type: application
framework:
  name: SAPUI5
  version: 1.80.1
resources:
  configuration:
    propertiesFileSourceEncoding: UTF-8
    paths:
      webapp: /webapp
builder:
  cachebuster:
    signatureType: hash
  customTasks:
  - name: ui5-task-nwabap-deployer
    afterTask: generateVersionInfo
    configuration: 
      resources:
        pattern: "**/*.*"
      connection:
        server: https://xxxxxxxxxxxxx:8300  
      authentication:
        user: XXXXX
        password: XXXXXXXXXXXXXXXXXXXXXX
      ui5:
        language: EN
        package: ZDEV
        bspContainer: ZXXXXXXXXX
        bspContainerText: UI5 Upload
        transportNo: XXXX000000
        calculateApplicationIndex: true   

```
