### ISSUE TITLE
ui5 deploy task doesn't respect customQueryParams

### ISSUE THREAD

**Issue by vobu** [pfefferf/ui5-nwabap-deployer#30]
ui5.yaml excerpt:
```yaml
builder:
  customTasks:
  - name: upload0
    afterTask: generateVersionInfo
    configuration:
      resources:
        pattern: '**/*'
      connection:
        server: http://my.box:12345
        customQueryParams:
          spnego: disabled
        client: 99
```

hitting of the deploy task via `ui5 build` then produces an authentication error that upon further investigation shows that in
`\ui5-nwabap-deployer-core\lib\AdtClient.js:98`
the parameter `oRequestOptions.url` doesn't contain the custom query parameters.

Actual: `http://my.box:12345/sap/bc/adt/filestore/ui5-bsp/objects/Z_BLA/content`
Expected: `http://my.box:12345/sap/bc/adt/filestore/ui5-bsp/objects/Z_BLA/content?spnego=disabled`

Thanks in advance for taking a look!
