### ISSUE TITLE
Variable in the configuration file

### ISSUE THREAD

**Issue by yramamurthy** [pfefferf/ui5-nwabap-deployer#7]
How do I refer to an environment variable in the ui5.yaml file? I wanted to avoid hard coding of user credentials in the example configuration file provided below. The idea is to have the environment variables set for user/password and to refer to these environment variables in the configuration file. Appreciate any inputs. Thank you.

```
specVersion: '1.0'
metadata:
  name: ui5proj1
type: application
builder:
  customTasks:
  - name: ui5-task-nwabap-deployer
    afterTask: generateVersionInfo
    configuration: 
      resources:
        pattern: "**/*.*"
      connection:
        server: https://host:port
        client: 100
        useStrictSSL: false 
      authentication:
        user: xxx
        password: xxx
```
